graph:
  api_key: "214ad8fea4f34456c35952f32963b967"
  subgraph_id: "5zvR82QoaXYFyDEKLZ9t6v9adgnptxYpKpSbxtgVENFV"

fetch_pools:
  label: "may24"
  start_timestamp: 1714521600 
  end_timestamp: 1717113600
